In [2]:
import numpy as np
from scipy.linalg import svd

In [3]:
def print_calculate_svd(A):
    print(f'\nA {A.shape}')
    print(A)

    U, s, VT = svd(A)
    print(f'\nU {U.shape}')
    print(U.round(6))
    print(f'\ns {s.shape}')
    print(s.round(6))
    print(f'\nVT {VT.shape}')
    print(VT.round(2))
    
    Sigma = np.zeros((A.shape))
    print(f'\nSigma {Sigma.shape}')
    print(Sigma.round(2))

    min_size = min(A.shape)
    Sigma[:min_size, :min_size] = np.diag(s)
    print(f'\nSigma {Sigma.shape}')
    print(Sigma.round(2))

    B = U.dot(Sigma.dot(VT))
    print(f'\nB {B.shape}')
    print(B)


In [4]:
A = np.array([
    [0, 1],
    [1, 1],
])
print_calculate_svd(A)


A (2, 2)
[[0 1]
 [1 1]]

U (2, 2)
[[-0.525731 -0.850651]
 [-0.850651  0.525731]]

s (2,)
[1.618034 0.618034]

VT (2, 2)
[[-0.53 -0.85]
 [ 0.85 -0.53]]

Sigma (2, 2)
[[0. 0.]
 [0. 0.]]

Sigma (2, 2)
[[1.62 0.  ]
 [0.   0.62]]

B (2, 2)
[[0. 1.]
 [1. 1.]]


In [4]:
B = np.array([
    [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
])

print_calculate_svd(B)


A (3, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

U (3, 3)
[[-0.191012  0.892663  0.408248]
 [-0.513719  0.263489 -0.816497]
 [-0.836426 -0.365685  0.408248]]

s (3,)
[96.965734  7.255783  0.      ]

VT (10, 10)
[[-0.24 -0.26 -0.27 -0.29 -0.3  -0.32 -0.34 -0.35 -0.37 -0.38]
 [-0.54 -0.43 -0.32 -0.21 -0.1   0.01  0.12  0.23  0.34  0.44]
 [-0.72  0.22  0.36  0.23  0.12  0.28 -0.35  0.06 -0.   -0.2 ]
 [-0.03 -0.18 -0.38  0.89 -0.08 -0.12  0.03 -0.07 -0.05 -0.01]
 [-0.08 -0.06 -0.31 -0.09  0.92 -0.12 -0.01 -0.1  -0.1  -0.07]
 [ 0.07  0.08 -0.47 -0.1  -0.08  0.84  0.04 -0.14 -0.14 -0.09]
 [-0.34  0.17  0.06 -0.02 -0.06 -0.08  0.86 -0.16 -0.19 -0.23]
 [-0.02  0.33 -0.33 -0.06 -0.07 -0.17 -0.03  0.8  -0.23 -0.22]
 [-0.03  0.45 -0.31 -0.04 -0.07 -0.17 -0.05 -0.23  0.73 -0.27]
 [-0.13  0.57 -0.16 -0.02 -0.06 -0.16 -0.11 -0.26 -0.32  0.65]]

Sigma (3, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 

In [5]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

print(f'\nA {A.shape}')
print(A)

U, s, VT = svd(A)
print(f'\nU {U.shape}')
print(U.round(6))
print(f'\ns {s.shape}')
print(s.round(6))
print(f'\nVT {VT.shape}')
print(VT.round(2))

Sigma = np.zeros((A.shape))
print(f'\nSigma {Sigma.shape}')
print(Sigma)

min_size = min(A.shape)
Sigma[:min_size, :min_size] = np.diag(s)
print(f'\nSigma {Sigma.shape}')
print(Sigma)

B = U.dot(Sigma.dot(VT))
print(f'\nB {B.shape}')
print(B)



A (3, 2)
[[1 2]
 [3 4]
 [5 6]]

U (3, 3)
[[-0.229848  0.883461  0.408248]
 [-0.524745  0.240782 -0.816497]
 [-0.819642 -0.401896  0.408248]]

s (2,)
[9.525518 0.514301]

VT (2, 2)
[[-0.62 -0.78]
 [-0.78  0.62]]

Sigma (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Sigma (3, 2)
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

B (3, 2)
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [7]:
A = np.array([
    [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
])
print(f'\nA {A.shape}')
print(A)

U, s, VT = svd(A)
print(f'\nU {U.shape}')
print(U.round(6))
print(f'\ns {s.shape}')
print(s.round(6))
print(f'\nVT {VT.shape}')
print(VT.round(2))

Sigma = np.zeros((A.shape))
print(f'\nSigma {Sigma.shape}')
print(Sigma.round(2))

min_size = min(A.shape)
Sigma[:min_size, :min_size] = np.diag(s)
print(f'\nSigma {Sigma.shape}')
print(Sigma.round(2))

n_elements = 2
Sigma = Sigma[:, :n_elements]
print(f'\nSigma {Sigma.shape}')
print(Sigma.round(2))

VT = VT[:n_elements, :]
print(f'\nVT {VT.shape}')
print(VT.round(2))

B = U.dot(Sigma.dot(VT))
print(f'\nB {B.shape}')
print(B)

T = U.dot(Sigma)
print(f'\nT {T.shape}')
print(T)

T = A.dot(VT.T)
print(f'\nT {T.shape}')
print(T)



A (3, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

U (3, 3)
[[-0.191012  0.892663  0.408248]
 [-0.513719  0.263489 -0.816497]
 [-0.836426 -0.365685  0.408248]]

s (3,)
[96.965734  7.255783  0.      ]

VT (10, 10)
[[-0.24 -0.26 -0.27 -0.29 -0.3  -0.32 -0.34 -0.35 -0.37 -0.38]
 [-0.54 -0.43 -0.32 -0.21 -0.1   0.01  0.12  0.23  0.34  0.44]
 [-0.72  0.22  0.36  0.23  0.12  0.28 -0.35  0.06 -0.   -0.2 ]
 [-0.03 -0.18 -0.38  0.89 -0.08 -0.12  0.03 -0.07 -0.05 -0.01]
 [-0.08 -0.06 -0.31 -0.09  0.92 -0.12 -0.01 -0.1  -0.1  -0.07]
 [ 0.07  0.08 -0.47 -0.1  -0.08  0.84  0.04 -0.14 -0.14 -0.09]
 [-0.34  0.17  0.06 -0.02 -0.06 -0.08  0.86 -0.16 -0.19 -0.23]
 [-0.02  0.33 -0.33 -0.06 -0.07 -0.17 -0.03  0.8  -0.23 -0.22]
 [-0.03  0.45 -0.31 -0.04 -0.07 -0.17 -0.05 -0.23  0.73 -0.27]
 [-0.13  0.57 -0.16 -0.02 -0.06 -0.16 -0.11 -0.26 -0.32  0.65]]

Sigma (3, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 